import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/committeespage">Committeespage</Link>
        </li>
        <li>
          <Link to="/mainframe">Mainframe</Link>
        </li>
        <li>
          <Link to="/speakers">Speakers</Link>
        </li>
        <li>
          <Link to="/aboutsection">Aboutsection</Link>
        </li>
        <li>
          <Link to="/contactuspage">ContactUspage</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
